### PR TITLE
this is my second commit

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ThantZinPhyo-SyS** [comment]
my second commit

**Comment by ThantZinPhyo-SyS** [comment]
third commit pr

**Comment by ThantZinPhyo-SyS** [comment]
gg

**Comment by ThantZinPhyo-SyS** [comment]
javascript

**Review by ghost — COMMENTED** [review]
javascript

**Comment by ThantZinPhyo-SyS** [comment]
javascript

**Review by ghost — COMMENTED** [review]
javascript

**Review by ghost — COMMENTED** [review]
javascript

**Review by ghost — COMMENTED** [review]
javascript

**Pull request closed without merging**
